plakaSorgu = "Plaka Giriniz: "
renkSorgu = "Marka Giriniz: "
markaSorgu = "Marka Giriniz: "
modelSorgu = "Model Giriniz: "
kmSorgu = "KM Değeri Giriniz: "
frigoSorgu = "Araç Frigorifik Soğutuculu mu? (Yalnızca 'Evet' ya da 'Hayır' Giriniz): "
isActiveSorgu = "Araç Şirket Adına Çalışır Durumda mı?(Yalnızca 'Evet' ya da 'Hayır' Giriniz): "